### ISSUE TITLE
[MongoDB] Implement file versioning

### ISSUE THREAD

**Issue by AlexandreBrg** [polydrive/polydrive#22]
When #14  is done, we must be able to store every single version of files into mongoDB. 

When an update is down / deletion, describe a way to create several versions of the same file. 

Questions: 

* Will APIs be impacted by this change ? 
* What data is needed from client for each version in addition to currently held data ? 
* What happens when a file is deleted ? Is it a version or the data is deleted ?

**Comment by NelopsisCode** [comment]
We have to change update and delete function. They will create a new document instead of update/delete it. 
The new document will have a new version. 

We create a new version of file when it is deleted to allow its recovery.

In Database, a document have a version number in addition to the other data.
